# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3dfcb216de8f2b485fe14389a9361ef7ce748bc5de81cb5e3f7ea35a3e850145996d2a2e96885317302a8f939584f6cc84ae5fd44fc55c1ebae36d39d487919

test:
  secret_key_base: 8d7a7bf11c81e82b412762ec31f2b591f8582e3b6f36087e62a703b669767bea3463524bd6742e97ec5cedcb2ab6590eb30d5a73f5c43efba85672e12ffe293e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
